src/Entity/Buy.php
<?php

namespace App\Entity;

use App\Repository\BuyRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BuyRepository::class)]
class Buy
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?BuyVacin $BuyVacin = null;

    #[ORM\ManyToOne]
    private ?User $user = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 12, scale: '0')]
    private ?string $total_payment = null;

    #[ORM\Column(length: 100)]
    private ?string $id_ml = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'Buy')]
    private ?PromotionSistem $promotionSistem = null;

    #[ORM\ManyToOne]
    private ?Products $Product_id = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $Date = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $Time = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable('now');
        $this->status = 'pending';
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBuyVacin(): ?BuyVacin
    {
        return $this->BuyVacin;
    }

    public function setBuyVacin(BuyVacin $BuyVacin): self
    {
        $this->BuyVacin = $BuyVacin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getTotalPayment(): ?string
    {
        return $this->total_payment;
    }

    public function setTotalPayment(string $total_payment): self
    {
        $this->total_payment = $total_payment;

        return $this;
    }

    public function getIdMl(): ?string
    {
        return $this->id_ml;
    }

    public function setIdMl(string $id_ml): self
    {
        $this->id_ml = $id_ml;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPromotionSistem(): ?PromotionSistem
    {
        return $this->promotionSistem;
    }

    public function setPromotionSistem(?PromotionSistem $promotionSistem): self
    {
        $this->promotionSistem = $promotionSistem;

        return $this;
    }

    public function getProductId(): ?Products
    {
        return $this->Product_id;
    }

    public function setProductId(Products $Product_id): self
    {
        $this->Product_id = $Product_id;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->Date;
    }

    public function setDate(?string $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTime(): ?string
    {
        return $this->Time;
    }

    public function setTime(?string $Time): self
    {
        $this->Time = $Time;

        return $this;
    }
}

src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 655)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 12, scale: '0')]
    private ?string $price = null;

    #[ORM\ManyToOne(inversedBy: 'product_id')]
    private ?Category $category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageFilename = null;

    #[ORM\ManyToOne(inversedBy: 'Product')]
    private ?PromotionSistem $promotionSistem = null;

    #[ORM\Column]
    private array $Status = [];

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImageFile(): ?UploadedFile
    {
        return $this->imageFile;
    }

    public function setImageFile(?UploadedFile $imageFile): self
    {
        $this->imageFile = $imageFile;

        if ($this->imageFilename) {
            // force the preUpdate and prePersist events to re-upload the image
            $this->imageFilename = null;
        }

        return $this;
    }

    public function setImageFileFromString(string $imageString): self
    {
        $this->imageFile = new File($imageString);
        return $this;
    }

    public function getImageFilePath(): ?string
    {
        return $this->imageFilename ? 'uploads/images/' . $this->imageFilename : null;
    }

    public function getImageFileUrl(): ?string
    {
        return $this->imageFilename ? '/uploads/images/' . $this->imageFilename : null;
    }

    public function getWebImagePath(): ?string
    {
        return $this->getImageFilePath() ? '/uploads/images/' . $this->imageFilename : null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getPromotionSistem(): ?PromotionSistem
    {
        return $this->promotionSistem;
    }

    public function setPromotionSistem(?PromotionSistem $promotionSistem): self
    {
        $this->promotionSistem = $promotionSistem;

        return $this;
    }

    public function getStatus(): array
    {
        return $this->Status;
    }

    public function setStatus(array $Status): self
    {
        $this->Status = $Status;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Expr\Array_;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 140)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    #[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[UniqueEntity(fields: ['telefone'], message: 'There is already an account with this telefone')]
    private ?string $telefone = null;

    #[ORM\Column(length: 11)]
    #[UniqueEntity(fields: ['cpf'], message: 'There is already an account with this cpf')]
    private ?string $cpf = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Buy::class)]
    private Collection $buy;

    public function __construct()
    {
        $this->buy = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getTelefone(): ?string
    {
        return $this->telefone;
    }

    public function setTelefone(string $telefone): self
    {
        $this->telefone = $telefone;

        return $this;
    }

    public function getCpf(): ?string
    {
        return $this->cpf;
    }

    public function setCpf(string $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @return Collection<int, Buy>
     */
    public function getCreatedAt(): Collection
    {
        return $this->created_at;
    }

    public function addCreatedAt(Buy $createdAt): self
    {
        if (!$this->created_at->contains($createdAt)) {
            $this->created_at->add($createdAt);
            $createdAt->setUser($this);
        }

        return $this;
    }

    public function removeCreatedAt(Buy $createdAt): self
    {
        if ($this->created_at->removeElement($createdAt)) {
            // set the owning side to null (unless already changed)
            if ($createdAt->getUser() === $this) {
                $createdAt->setUser(null);
            }
        }

        return $this;
    }
}

templates/front/page/ProductById.html.twig
{% extends 'front/base.html.twig' %}

{% block content %}
    <div class="antialiased">

        <div class="py-6">
            {% for product in products %}
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6">
                <div class="flex flex-col md:flex-row -mx-4">
                    <div class="md:flex-1 px-4">
                        <div x-data="{ image: 1 }" x-cloak>
                            <div class="h-full md:h-80 rounded-lg bg-gray-100 mb-4">
                                <div class="h-full md:h-80 rounded-lg bg-cover bg-center bg-[url({{ asset('uploads/products/' ~ product.imageFilename) }})]"></div>
                            </div>

                            <div class="flex -mx-2 mb-4">
                                <template x-for="i in 4">
                                    <div class="flex-1 px-2">
                                        <button x-on:click="image = i" :class="{ 'ring-2 ring-indigo-300 ring-inset': image === i }" class="focus:outline-none w-full rounded-lg h-24 md:h-32 bg-gray-100 flex items-center justify-center">
                                            <span x-text="i" class="text-2xl"></span>
                                        </button>
                                    </div>
                                </template>
                            </div>
                        </div>
                    </div>
                    <div class="md:flex-1 px-4">
                         <h2 class="mb-2 leading-tight tracking-tight font-bold text-gray-800 text-2xl md:text-3xl">{{ product.name }}</h2>
                        <p class="text-gray-500 text-sm">Por <a href="#" class="text-indigo-600 hover:underline">ImunoVacin</a></p>

                        <div class="flex items-center space-x-4 my-4">
                            <div>
                                <div class="rounded-lg bg-gray-100 flex py-2 px-3">
                                    <span class="text-indigo-400 mr-1 mt-1">R$:</span>
                                    <span class="font-bold text-indigo-600 text-3xl">{{ product.price|number_format(2, ',', '.') }}</span>
                                </div>
                            </div>
                        </div>

                        <p class="text-gray-500">{{ product.description }}</p>
                        <form id="add-to-cart-form" method="post" action="{{ path('app_buy_vacin')}}">
                        <input type="hidden" value="" name="school" id="school">
                        <input type="hidden" value="1" name="quantity" id="quantity">
                        <input type="hidden" name="id_product" id="id_product" value="{{ product.id }}">
                        <div class="flex py-4 space-x-4">
                            <div class="relative">
                                <div class="text-center left-0 pt-2 right-0 absolute block text-xs uppercase text-gray-400 tracking-wide font-semibold">Qnt</div>
                                <select name="mySelect" id="mySelect" class="cursor-pointer appearance-none rounded-xl border border-gray-200 pl-4 pr-8 h-14 flex items-end pb-1">
                                    <option selected>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>

                                <svg class="w-5 h-5 text-gray-400 absolute right-0 bottom-0 mb-2 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 9l4-4 4 4m0 6l-4 4-4-4" />
                                </svg>
                            </div>
                            {% if is_granted('ROLE_USER') %}
                                <button type="submit" class="h-14 px-6 py-2 font-semibold rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white">
                                    Adicionar ao Carrinho
                                </button>
                            {% else %}
                                <button disabled type="submit" class="h-14 px-6 py-2 font-semibold rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white">
                                    Adicionar ao Carrinho
                                </button>
                            {% endif %}

                        </div>
                        <div class="sm:col-span-2">
                            <label for="message" class="block text-sm font-semibold leading-6 text-gray-900">Outras Informações</label>
                            <div class="mt-2.5">
                                <textarea name="OthersVacinated" id="OthersVacinated" placeholder="Outros recebedores NOME|CPF" rows="4" class="block w-full rounded-md border-0 py-2 px-3.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
                            </div>
                        </div>


                        <script>
                            var select = document.getElementById('mySelect');
                            var meuInput = document.getElementById('quantity');

                            select.addEventListener('change', function() {
                                meuInput.value = select.value;
                            });
                        </script>
                     </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/front/page/cliente.html.twig
{% extends 'front/base.html.twig' %}

{% block content %}
    <!-- This example requires Tailwind CSS v2.0+ -->
    <div class="bg-white">
        <div class="max-w-3xl mx-auto px-4 py-16 sm:px-6 sm:py-24">
            <div class="max-w-xl">
                <h1 id="your-orders-heading" class="text-3xl font-extrabold tracking-tight text-gray-900">Minhas Compras</h1>
                <p class="mt-2 text-sm text-gray-500">Acompanhe o status de suas compras pelo nosso site</p>
            </div>

            {% if compras is empty %}
                <br/>
                <div class="bg-gray-50 px-4 py-6 sm:rounded-lg sm:p-6 md:flex md:items-center md:justify-between md:space-x-6 lg:space-x-8">
                    <dl class="divide-gray-200 text-lg font-extrabold text-gray-600 flex-auto">
                        <div class="flex justify-between pt-4 font-extrabold text-gray-900 md:block md:pt-0">
                            <h1 class="font-lg font-extrabold">Você ainda não fez uma compra</h1>
                        </div>
                    </dl>
                    <div class="space-y-4 mt-6 sm:flex sm:space-x-4 sm:space-y-0 md:mt-0">
                        <a href="{{ path('app_page') }}" class="w-full flex items-center justify-center bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 md:w-auto">
                            Comprar Agora
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="mt-12 space-y-16 sm:mt-16">
                    {% for compra in compras %}
                        {% set statusPayment = compra.status %}
                        {% set status = '' %}
                        {% if 'approved' in statusPayment %}
                            {% set status = 'Aprovado' %}
                        {% elseif 'pending' in statusPayment %}
                            {% set status = 'Pendente' %}
                        {% endif %}
                        <section aria-labelledby="4376-heading">
                            <div class="space-y-1 md:flex md:items-baseline md:space-y-0 md:space-x-4">
                                <h2 id="4376-heading" class="text-lg font-medium text-gray-900 md:flex-shrink-0">Pedido #{{ compra.id }}</h2>
                                <div class="space-y-5 md:flex-1 md:min-w-0 sm:flex sm:items-baseline sm:justify-between sm:space-y-0">
                                    <p class="text-sm font-medium text-gray-500"></p>
                                    <div class="flex text-sm font-medium">
                                        <a href="#" class="text-indigo-600 hover:text-indigo-500">Status do Pagamento</a>
                                        <div class="border-l border-gray-200 ml-4 pl-4 sm:ml-6 sm:pl-6">
                                            <a href="#" class="text-indigo-600 hover:text-indigo-500">{{ status }}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="mt-6 -mb-6 flow-root border-t border-gray-200 divide-y divide-gray-200">
                                <div class="py-6 sm:flex">
                                    <div class="flex space-x-4 sm:min-w-0 sm:flex-1 sm:space-x-6 lg:space-x-8">
                                        <img src="{{ asset('uploads/products/' ~ compra.productId.imageFilename) }}" alt="product image" class="flex-none w-20 h-20 rounded-md object-center object-cover sm:w-48 sm:h-48">
                                        <div class="pt-1.5 min-w-0 flex-1 sm:pt-0">
                                            <h3 class="text-sm font-medium text-gray-900">
                                                <a href="#">{{ compra.productId.name }}</a>
                                            </h3>
                                            <h3 class="px-6 py-4">{{ compra.PromotionSistem.name ?? '' }}</h3>
                                            <p class="text-sm text-gray-500 truncate">
                                                <span>Quantidade</span>
                                                <span class="mx-1 text-gray-400" aria-hidden="true">&middot;</span>
                                                <span>{{ compra.BuyVacin.quantity|number_format(0, '.', '') }}</span>
                                            </p>
                                            <p class="mt-1 font-medium text-gray-500">R$: {{ compra.productId.price|number_format(2, ',', '.') }}</p>

                                            <p class="text-lg text-gray-900 truncate">
                                                <span>Total</span>
                                                <span class="mx-1 text-gray-400" aria-hidden="true">&middot;</span>
                                                <span>R$: {{ compra.totalPayment }}</span>
                                            </p>

                                            <br/>
                                            <p class="text-lg text-gray-900 truncate">
                                                <span class="mx-1 text-gray-400" aria-hidden="true">{{ compra.date }}</span>
                                                <span>as {{ compra.time }}</span>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="mt-6 space-y-4 sm:mt-0 sm:ml-6 sm:flex-none sm:w-40">
                                        <button type="button" class="w-full flex items-center justify-center bg-indigo-600 py-2 px-2.5 border border-transparent rounded-md shadow-sm text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:w-full sm:flex-grow-0"><a href="{{ path('app_page') }}">Comprar Novamente<a/></button>
                                    </div>
                                </div>
                            </div>
                        </section>
                    {% endfor %}
                    <br/>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/front/page/index.html.twig
{% extends 'front/base.html.twig' %}

{% block content %}
{{ include('front/components/banner.html.twig') }}
{{ render(controller('App\\Controller\\user\\ProductsController::index')) }}
    <br/>
    {{ include('front/components/_teamSection.html.twig') }}
    {{ include('front/components/feedback.html.twig') }}
    <br/>
    {{ include('front/components/faq.html.twig') }}
    {{ include('front/components/empresas.html.twig') }}
{% endblock %}