src/Entity/BuyVacin.php
<?php

namespace App\Entity;

use App\Repository\BuyVacinRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BuyVacinRepository::class)]
class BuyVacin
{
    private $Product;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: '2')]
    private ?string $Quantity = null;

    #[ORM\Column(length: 255)]
    private ?string $OthersVacinated = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?SchoolVacin $schoolId = null;

    #[ORM\ManyToOne(inversedBy: 'BuyVacin')]
    private ?PromotionSistem $promotionSistem = null;

    #[ORM\ManyToOne]
    private ?Products $Product_id = null;

    public function __construct()
    {
        $this->SchoolId = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->Quantity;
    }

    public function setQuantity(string $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getOthersVacinated(): ?string
    {
        return $this->OthersVacinated;
    }

    public function setOthersVacinated(string $OthersVacinated): self
    {
        $this->OthersVacinated = $OthersVacinated;

        return $this;
    }

    /**
     * @return Collection<int, SchoolVacin>
     */
    public function getSchoolId(): Collection
    {
        return $this->SchoolId;
    }

    public function addSchoolId(SchoolVacin $schoolId): self
    {
        if (!$this->SchoolId->contains($schoolId)) {
            $this->SchoolId->add($schoolId);
            $schoolId->setSchoolId($this);
        }

        return $this;
    }

    public function removeSchoolId(SchoolVacin $schoolId): self
    {
        if ($this->SchoolId->removeElement($schoolId)) {
            // set the owning side to null (unless already changed)
            if ($schoolId->getSchoolId() === $this) {
                $schoolId->setSchoolId(null);
            }
        }

        return $this;
    }

    public function setSchoolId(?SchoolVacin $schoolId): self
    {
        $this->schoolId = $schoolId;

        return $this;
    }

    public function getPromotionSistem(): ?PromotionSistem
    {
        return $this->promotionSistem;
    }

    public function setPromotionSistem(?PromotionSistem $promotionSistem): self
    {
        $this->promotionSistem = $promotionSistem;

        return $this;
    }

    public function getProduct()
    {
        return $this->Product;
    }

    public function setProduct(Products $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getProductId(): ?Products
    {
        return $this->Product_id;
    }

    public function setProductId(?Products $Product_id): self
    {
        $this->Product_id = $Product_id;

        return $this;
    }
}

templates/front/components/_ListBuyUser.html.twig
<div class="flex font-sans">
    <div class="flex-none w-48 relative">
        <img src="/classic-utility-jacket.jpg" alt="" class="absolute inset-0 w-full h-full object-cover" loading="lazy" />
    </div>
    <form class="flex-auto p-6">
        <div class="flex flex-wrap">
            <h1 class="flex-auto text-lg font-semibold text-slate-900">
                Classic Utility Jacket
            </h1>
            <div class="text-lg font-semibold text-slate-500">
                $110.00
            </div>
            <div class="w-full flex-none text-sm font-medium text-slate-700 mt-2">
                In stock
            </div>
        </div>
        <div class="flex items-baseline mt-4 mb-6 pb-6 border-b border-slate-200">
            <div class="space-x-2 flex text-sm">
                <label>
                    <input class="sr-only peer" name="size" type="radio" value="xs" checked />
                    <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                        XS
                    </div>
                </label>
                <label>
                    <input class="sr-only peer" name="size" type="radio" value="s" />
                    <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                        S
                    </div>
                </label>
                <label>
                    <input class="sr-only peer" name="size" type="radio" value="m" />
                    <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                        M
                    </div>
                </label>
                <label>
                    <input class="sr-only peer" name="size" type="radio" value="l" />
                    <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                        L
                    </div>
                </label>
                <label>
                    <input class="sr-only peer" name="size" type="radio" value="xl" />
                    <div class="w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
                        XL
                    </div>
                </label>
            </div>
        </div>
        <div class="flex space-x-4 mb-6 text-sm font-medium">
            <div class="flex-auto flex space-x-4">
                <button class="h-10 px-6 font-semibold rounded-md bg-black text-white" type="submit">
                    Buy now
                </button>
                <button class="h-10 px-6 font-semibold rounded-md border border-slate-200 text-slate-900" type="button">
                    Add to bag
                </button>
            </div>
            <button class="flex-none flex items-center justify-center w-9 h-9 rounded-md text-slate-300 border border-slate-200" type="button" aria-label="Like">
                <svg width="20" height="20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" />
                </svg>
            </button>
        </div>
        <p class="text-sm text-slate-700">
            Free shipping on all continental US orders.
        </p>
    </form>
</div>

templates/front/components/_categoryList.html.twig
<section aria-labelledby="category-heading" class="pt-24 sm:pt-32 xl:max-w-7xl xl:mx-auto xl:px-8">
    <div class="px-4 sm:px-6 sm:flex sm:items-center sm:justify-between lg:px-8 xl:px-0">
        <h2 id="category-heading" class="text-2xl font-extrabold tracking-tight text-gray-900">Compre por Categoria</h2>
    </div>

    <div class="mt-4 flow-root">
        <div class="-my-2">
            <div class="box-content py-2 relative h-80 overflow-x-auto xl:overflow-visible">
                <div class="absolute min-w-screen-xl px-4 flex space-x-8 sm:px-6 lg:px-8 xl:relative xl:px-0 xl:space-x-0 xl:grid xl:grid-cols-5 xl:gap-x-8">
                {% for category in categorys %}
                    <a href="#" class="relative w-56 h-80 rounded-lg p-6 flex flex-col overflow-hidden hover:opacity-75 xl:w-auto">
                <span aria-hidden="true" class="absolute inset-0">
                  <img src="{{ asset('uploads/categorys/' ~ category.ImageFilename) }}" alt="" class="w-full h-full object-center object-cover">
                </span>
                        <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
                        <span class="relative mt-auto text-center text-xl font-bold text-white">{{ category.name }}</span>
                    </a>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

templates/front/components/_productsList.html.twig
<div class="bg-white">
    <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
        <h2 class="mb-3 text-2xl font-bold text-gray-700">Produtos</h2>

        <div class="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">

            {% for product in products %}
            <a href="{{ path('app_product_id', {'id': product.id}) }}" class="group">
                <div class="aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-w-7 xl:aspect-h-8">
                    <img src="{{ asset('uploads/products/' ~ product.imageFilename) }}" alt="{{ product.name }}" class="h-full w-full object-cover object-center group-hover:opacity-75">
                </div>
                <h1 class="mt-4 text-lg font-bold text-gray-700">{{ product.name }}</h1>
                <p class="mt-1 text-lg font-medium text-gray-900">R$: {{ product.price|number_format(2, ',', '.') }}</p>
            </a>
            {% endfor %}

        </div>
    </div>
</div>

templates/front/components/_teamSection.html.twig
<div class="bg-white py-24 sm:py-32">
    <div class="mx-auto grid max-w-7xl gap-y-20 gap-x-8 px-6 lg:px-8 xl:grid-cols-3">
        <div class="max-w-2xl">
            <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Conheça Nosso Time</h2>
            <p class="mt-6 text-lg leading-8 text-gray-600">Contamos com uma equipe especializada para melhor atender você e sua família.</p>
        </div>
        <ul role="list" class="grid gap-x-8 gap-y-12 sm:grid-cols-2 sm:gap-y-16 xl:col-span-2">
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Fernanda-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Fernanda Gomes</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Diretora Técnica</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Marina-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Marina Girotto</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Diretora Administrativa</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Antonio-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Antonio Carlos Girotto</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Médico Responsavel</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Barbara-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Bárbara Leal</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Enfermeira</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Lucicleide-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Lucileide</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Equipe de Enfermagem</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Lohaine-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Lohaine</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Equipe de Enfermagem</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Natalia-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Natália</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Secretaria</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="flex items-center gap-x-6">
                    <img class="h-16 w-16 rounded-full" src="https://imunovacin.com.br/wp-content/uploads/2022/02/Indaiatuba_Clinica_Infantil_Vacinas_Cleia-150x150.png" alt="">
                    <div>
                        <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">Cléia</h3>
                        <p class="text-sm font-semibold leading-6 text-indigo-600">Nossa "Mãezona"</p>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

templates/front/components/banner.html.twig
<div class="w-full bg-cover bg-center" style="height:32rem; background-image: url({{ asset('assets/banner.jpeg') }});">
    <div class="flex items-center justify-center h-full w-full bg-gray-900 bg-opacity-50">
    </div>
</div>

templates/front/components/carrossel.html.twig
<div
        id="carouselExampleIndicators"
        class="relative"
        data-te-carousel-init
        data-te-carousel-slide>
    <div
            class="absolute right-0 bottom-0 left-0 z-[2] mx-[15%] mb-4 flex list-none justify-center p-0"
            data-te-carousel-indicators>
        <button
                type="button"
                data-te-target="#carouselExampleIndicators"
                data-te-slide-to="0"
                data-te-carousel-active
                class="mx-[3px] box-content h-[3px] w-[30px] flex-initial cursor-pointer border-0 border-y-[10px] border-solid border-transparent bg-white bg-clip-padding p-0 -indent-[999px] opacity-50 transition-opacity duration-[600ms] ease-[cubic-bezier(0.25,0.1,0.25,1.0)] motion-reduce:transition-none"
                aria-current="true"
                aria-label="Slide 1"></button>
        <button
                type="button"
                data-te-target="#carouselExampleIndicators"
                data-te-slide-to="1"
                class="mx-[3px] box-content h-[3px] w-[30px] flex-initial cursor-pointer border-0 border-y-[10px] border-solid border-transparent bg-white bg-clip-padding p-0 -indent-[999px] opacity-50 transition-opacity duration-[600ms] ease-[cubic-bezier(0.25,0.1,0.25,1.0)] motion-reduce:transition-none"
                aria-label="Slide 2"></button>
        <button
                type="button"
                data-te-target="#carouselExampleIndicators"
                data-te-slide-to="2"
                class="mx-[3px] box-content h-[3px] w-[30px] flex-initial cursor-pointer border-0 border-y-[10px] border-solid border-transparent bg-white bg-clip-padding p-0 -indent-[999px] opacity-50 transition-opacity duration-[600ms] ease-[cubic-bezier(0.25,0.1,0.25,1.0)] motion-reduce:transition-none"
                aria-label="Slide 3"></button>
    </div>
    <div
            class="relative w-full overflow-hidden after:clear-both after:block after:content-['']">
        <div
                class="relative float-left -mr-[100%] w-full transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none"
                data-te-carousel-item
                data-te-carousel-active>
            <img
                    src="https://mdbcdn.b-cdn.net/img/new/slides/041.webp"
                    class="block w-full"
                    alt="Wild Landscape" />
        </div>
        <div
                class="relative float-left -mr-[100%] hidden w-full transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none"
                data-te-carousel-item>
            <img
                    src="https://mdbcdn.b-cdn.net/img/new/slides/042.webp"
                    class="block w-full"
                    alt="Camera" />
        </div>
        <div
                class="relative float-left -mr-[100%] hidden w-full transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none"
                data-te-carousel-item>
            <img
                    src="https://mdbcdn.b-cdn.net/img/new/slides/043.webp"
                    class="block w-full"
                    alt="Exotic Fruits" />
        </div>
    </div>
    <button
            class="absolute top-0 bottom-0 left-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-white opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-white hover:no-underline hover:opacity-90 hover:outline-none focus:text-white focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none"
            type="button"
            data-te-target="#carouselExampleIndicators"
            data-te-slide="prev">
    <span class="inline-block h-8 w-8">
      <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="h-6 w-6">
        <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M15.75 19.5L8.25 12l7.5-7.5" />
      </svg>
    </span>
        <span
                class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]"
        >Previous</span
        >
    </button>
    <button
            class="absolute top-0 bottom-0 right-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-white opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-white hover:no-underline hover:opacity-90 hover:outline-none focus:text-white focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none"
            type="button"
            data-te-target="#carouselExampleIndicators"
            data-te-slide="next">
    <span class="inline-block h-8 w-8">
      <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="h-6 w-6">
        <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M8.25 4.5l7.5 7.5-7.5 7.5" />
      </svg>
    </span>
        <span
                class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]"
        >Next</span
        >
    </button>
</div>

templates/front/components/empresas.html.twig
<div class="bg-white py-24 sm:py-32">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <blockquote class="text-center text-xl font-semibold leading-8 text-gray-900 sm:text-2xl sm:leading-9">
            <p>Algumas empresas parceiras ImunoVacin</p>
        </blockquote>
        <div class="mx-auto mt-10 grid max-w-lg grid-cols-4 items-center gap-x-8 gap-y-10 sm:max-w-xl sm:grid-cols-6 sm:gap-x-10 lg:mx-0 lg:max-w-none lg:grid-cols-5">
            <img class="col-span-2 max-h-12 w-full object-contain lg:col-span-1" src="{{ asset('assets/parceiros/irritec.png') }}" alt="Transistor" width="158" height="48">
            <img class="col-span-2 max-h-12 w-full object-contain lg:col-span-1" src="{{ asset('assets/parceiros/obj.png') }}" alt="Reform" width="158" height="48">
            <img class="col-span-2 max-h-12 w-full object-contain lg:col-span-1" src="{{ asset('assets/parceiros/mann-hummel.svg') }}" alt="Tuple" width="158" height="48">
            <img class="col-span-2 max-h-12 w-full object-contain sm:col-start-2 lg:col-span-1" src="{{ asset('assets/parceiros/pecval.jpeg') }}" alt="SavvyCal" width="158" height="48">
            <img class="col-span-2 col-start-2 max-h-12 w-full object-contain sm:col-start-auto lg:col-span-1" src="{{ asset('assets/parceiros/grow.png') }}" alt="Statamic" width="158" height="48">
        </div>
    </div>
</div>

templates/front/components/feedback.html.twig
<div class="mx-auto max-w-2xl lg:max-w-4xl">
    <blockquote class="text-center text-xl font-semibold leading-8 text-gray-900 sm:text-2xl sm:leading-9">
        <p>Alguns Feedbacks</p>
    </blockquote>
    <figure class="mt-10">
        <blockquote class="text-center text-xl font-semibold leading-8 text-gray-900 sm:text-2xl sm:leading-9">
            <p>“Excelente! Fomos super bem atendidos. Meu filho teve toda atenção, cuidado e no final ganhou um presentinho. Profissionais super qualificados. Parabéns Fernanda e toda equipe da ImunoVacin. Obrigada!”</p>
        </blockquote>
        <figcaption class="mt-10">
            <div class="mt-4 flex items-center justify-center space-x-3 text-base">
                <div class="font-semibold text-gray-900">Daniela Fernandes</div>
                <svg viewBox="0 0 2 2" width="3" height="3" aria-hidden="true" class="fill-gray-900">
                    <circle cx="1" cy="1" r="1" />
                </svg>
                <div class="text-gray-600">Cliente ImunoVacin</div>
            </div>
        </figcaption>
    </figure>
</div>

templates/front/components/header.html.twig
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-white">
    <div class="container flex flex-wrap items-center justify-between mx-auto">
        <a href="{{ path('app_page') }}" class="flex items-center">
            <img src="{{ asset('assets/logo-imuno.png') }}" class="h-14 mr-3 sm:h-14" alt="ImunoVacin Logo" />
        </a>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="mobile-menu-2">
            <ul class="flex items-center flex-col p-4 mt-4 border rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white">
                <li>
                    <a href="{{ path('app_page') }}" class="block py-2 pl-3 pr-4 text-grey-900 bg-grey-900 rounded md:bg-transparent md:text-grey-900 md:p-0 dark:text-grey-900" aria-current="page">Home</a>
                </li>
                <li>
                    <a href="#" class="block py-2 pl-3 pr-4 text-grey-900 rounded hover:bg-grey-900 md:hover:bg-transparent md:hover:text-grey-900 md:p-0 dark:text-grey-900 md:dark:hover:text-grey-900 dark:hover:bg-gray-700 dark:hover:text-grey-900 md:dark:hover:bg-transparent dark:border-gray-700">Sobre</a>
                </li>
                <li>
                    <a href="#" class="block py-2 pl-3 pr-4 text-grey-900 rounded hover:bg-grey-900 md:hover:bg-transparent md:hover:text-grey-900 md:p-0 dark:text-grey-900 md:dark:hover:text-grey-900 dark:hover:bg-gray-700 dark:hover:text-grey-900 md:dark:hover:bg-transparent dark:border-gray-700">Nossa Equipe</a>
                </li>
                <li>
                    <a href="#" class="block py-2 pl-3 pr-4 text-grey-900 rounded hover:bg-grey-900 md:hover:bg-transparent md:hover:text-grey-900 md:p-0 dark:text-grey-900 md:dark:hover:text-grey-900 dark:hover:bg-gray-700 dark:hover:text-grey-900 md:dark:hover:bg-transparent dark:border-gray-700">Feedback</a>
                </li>
                <li>
                    <a href="#" class="block py-2 pl-3 pr-4 text-grey-900 rounded hover:bg-grey-900 md:hover:bg-transparent md:hover:text-grey-900 md:p-0 dark:text-grey-900 md:dark:hover:text-grey-900 dark:hover:bg-gray-700 dark:hover:text-grey-900 md:dark:hover:bg-transparent dark:border-gray-700">Parceiros</a>
                </li>
                <li>
                    <button type="button" class="block py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"><a href="{{ path(app.user ? 'app_user_minhas_compras' : 'app_user_login') }}" class="block py-2 pl-3 pr-4 text-white rounded hover:bg-gray-100 md:hover:bg-black md:hover:text-grey-900 md:p-0 dark:text-grey-900 md:dark:hover:text-grey-900 dark:hover:bg-gray-700 dark:hover:text-grey-900 md:dark:hover:bg-transparent dark:border-gray-700">Minhas Compras</a></button>
                </li>
                {% if is_granted('ROLE_USER') %}
                    <li>
                        <a href="{{ path('app_logout') }}" class=" block py-2 pl-3 pr-4 text-grey-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-grey-900 md:p-0 dark:text-grey-900 md:dark:hover:text-grey-900 dark:hover:bg-gray-700 dark:hover:text-grey-900 md:dark:hover:bg-transparent dark:border-gray-700">Logout</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>